[build]
  functions = "functions"
  command = "yarn run build"
  publish = "dist"

[functions]
  external_node_modules = ["astro"]

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/resume"
  to = "https://bit.ly/2Tbfyqx"
  status = 301

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/abdulsamad-ansari"
  status = 301

[[redirects]]
  from = "/github"
  to = "https://github.com/abdulsamad"
  status = 301

[[redirects]]
  from = "/telegram"
  to = "https://t.me/AbdulSamadDev"
  status = 301

[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/AbdulSamadDev"
  status = 301

[[headers]]
	for = "/*"

	[headers.values]
		X-Frame-Options = "DENY"

# [[headers]]
#   for = "*.js"
#   [headers.values]
#     Cache-Control = "public, max-age=604800"
# [[headers]]
#   for = "*.css"
#   [headers.values]
#     Cache-Control = "public, max-age=604800"