name = "abdulsamad"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-05-04"
compatibility_flags = ["nodejs_compat"]


[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
