name = "abdulsamad"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[vars]
POSTHOG_UPSTREAM_HOST = "https://us.i.posthog.com"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
